services:
  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: npm ci --prefer-offline && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
