# Render deployment configuration
services:
  - type: web
    name: ecommerce-app
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: starter
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce_backend.settings
      - key: PYTHON_VERSION
        value: 3.9.19
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: e-comerce-drf-reactjs.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://e-comerce-drf-reactjs.onrender.com
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: starter
